
// This file has been generated by the GUI designer. Do not modify.
namespace CodeDistribution.Pad
{
	public partial class MainWidget
	{
		private global::Gtk.VBox RootVBox;

		private global::Gtk.HBox ToolbarHBox;

		private global::Gtk.Button ReloadButton;

		private global::Gtk.Button PreferencesButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CodeDistribution.Pad.MainWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "CodeDistribution.Pad.MainWidget";
			// Container child CodeDistribution.Pad.MainWidget.Gtk.Container+ContainerChild
			this.RootVBox = new global::Gtk.VBox();
			this.RootVBox.Name = "RootVBox";
			this.RootVBox.Spacing = 6;
			// Container child RootVBox.Gtk.Box+BoxChild
			this.ToolbarHBox = new global::Gtk.HBox();
			this.ToolbarHBox.Name = "ToolbarHBox";
			this.ToolbarHBox.Spacing = 6;
			// Container child ToolbarHBox.Gtk.Box+BoxChild
			this.ReloadButton = new global::Gtk.Button();
			this.ReloadButton.CanFocus = true;
			this.ReloadButton.Name = "ReloadButton";
			this.ReloadButton.UseUnderline = true;
			this.ReloadButton.Label = global::Mono.Unix.Catalog.GetString("Reload");
			this.ToolbarHBox.Add(this.ReloadButton);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.ToolbarHBox[this.ReloadButton]));
			w1.Position = 0;
			w1.Padding = ((uint)(4));
			// Container child ToolbarHBox.Gtk.Box+BoxChild
			this.PreferencesButton = new global::Gtk.Button();
			this.PreferencesButton.CanFocus = true;
			this.PreferencesButton.Name = "PreferencesButton";
			this.PreferencesButton.UseUnderline = true;
			global::Gtk.Image w2 = new global::Gtk.Image();
			w2.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-preferences", global::Gtk.IconSize.Menu);
			this.PreferencesButton.Image = w2;
			this.ToolbarHBox.Add(this.PreferencesButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.ToolbarHBox[this.PreferencesButton]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(4));
			this.RootVBox.Add(this.ToolbarHBox);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.RootVBox[this.ToolbarHBox]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.Add(this.RootVBox);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.ReloadButton.Clicked += new global::System.EventHandler(this.HandleReloadClicked);
			this.PreferencesButton.Clicked += new global::System.EventHandler(this.HandlePreferencesClicked);
		}
	}
}
